// National teams: canonical names (as football-data.org spells them where known),
// FIFA codes, and the other names broadcasters use in titles (English variants and
// the Spanish/French/German/Italian names that show up on federation channels).
// Used for World Cup / Euros fixture matching and for discovering Nations League
// matches from video titles.

export const NATIONS = [
  ['England', 'ENG', 'inglaterra angleterre inghilterra'],
  ['Spain', 'ESP', 'espana espagne spagna spanien'],
  ['Germany', 'GER', 'alemania deutschland allemagne germania'],
  ['France', 'FRA', 'francia frankreich'],
  ['Italy', 'ITA', 'italia italie italien'],
  ['Portugal', 'POR', 'portogallo'],
  ['Netherlands', 'NED', 'holland paises bajos pays bas niederlande olanda'],
  ['Belgium', 'BEL', 'belgica belgique belgien belgio'],
  ['Switzerland', 'SUI', 'suiza suisse schweiz svizzera'],
  ['Croatia', 'CRO', 'croacia croatie kroatien croazia hrvatska'],
  ['Denmark', 'DEN', 'dinamarca danemark daenemark danimarca'],
  ['Norway', 'NOR', 'noruega norvege norwegen norvegia'],
  ['Sweden', 'SWE', 'suecia suede schweden svezia'],
  ['Poland', 'POL', 'polonia pologne polen polska'],
  ['Austria', 'AUT', 'osterreich autriche'],
  ['Scotland', 'SCO', 'escocia ecosse schottland scozia'],
  ['Wales', 'WAL', 'gales pays de galles'],
  ['Northern Ireland', 'NIR', 'irlanda del norte'],
  ['Republic of Ireland', 'IRL', 'ireland irlanda irlande'],
  ['Finland', 'FIN', 'finlandia finnland'],
  ['Iceland', 'ISL', 'islandia islande'],
  ['Czechia', 'CZE', 'czech republic chequia tchequie tschechien'],
  ['Slovakia', 'SVK', 'eslovaquia slovaquie slowakei'],
  ['Slovenia', 'SVN', 'eslovenia slovenie slowenien'],
  ['Hungary', 'HUN', 'hungria hongrie ungarn ungheria'],
  ['Romania', 'ROU', 'rumania roumanie rumanien'],
  ['Bulgaria', 'BUL', 'bulgarie bulgarien'],
  ['Serbia', 'SRB', 'serbie serbien'],
  ['Montenegro', 'MNE', ''],
  ['Bosnia and Herzegovina', 'BIH', 'bosnia bosnia herzegovina'],
  ['North Macedonia', 'MKD', 'fyr macedonia macedonia del norte'],
  ['Albania', 'ALB', 'albanie albanien'],
  ['Kosovo', 'KVX', ''],
  ['Greece', 'GRE', 'grecia grece griechenland'],
  ['Turkey', 'TUR', 'turkiye turquia turquie turkei'],
  ['Cyprus', 'CYP', 'chipre chypre zypern'],
  ['Israel', 'ISR', ''],
  ['Ukraine', 'UKR', 'ucrania ukraine'],
  ['Belarus', 'BLR', 'bielorrusia'],
  ['Russia', 'RUS', 'rusia'],
  ['Georgia', 'GEO', ''],
  ['Armenia', 'ARM', ''],
  ['Azerbaijan', 'AZE', 'azerbaiyan'],
  ['Kazakhstan', 'KAZ', 'kazajistan'],
  ['Estonia', 'EST', ''],
  ['Latvia', 'LVA', 'letonia'],
  ['Lithuania', 'LTU', 'lituania'],
  ['Moldova', 'MDA', ''],
  ['Luxembourg', 'LUX', 'luxemburgo luxemburg'],
  ['Liechtenstein', 'LIE', ''],
  ['Malta', 'MLT', ''],
  ['Andorra', 'AND', ''],
  ['San Marino', 'SMR', ''],
  ['Gibraltar', 'GIB', ''],
  ['Faroe Islands', 'FRO', 'islas feroe faroe'],
  // Rest of the world (World Cup)
  ['Brazil', 'BRA', 'brasil bresil brasilien'],
  ['Argentina', 'ARG', 'argentine argentinien'],
  ['Uruguay', 'URU', ''],
  ['Colombia', 'COL', 'colombie kolumbien'],
  ['Ecuador', 'ECU', 'equateur'],
  ['Paraguay', 'PAR', ''],
  ['Chile', 'CHI', 'chili'],
  ['Peru', 'PER', ''],
  ['Venezuela', 'VEN', ''],
  ['Bolivia', 'BOL', ''],
  ['United States', 'USA', 'usa usmnt estados unidos etats unis'],
  ['Mexico', 'MEX', 'mexique mexiko messico'],
  ['Canada', 'CAN', ''],
  ['Costa Rica', 'CRC', ''],
  ['Panama', 'PAN', ''],
  ['Jamaica', 'JAM', ''],
  ['Honduras', 'HON', ''],
  ['Haiti', 'HAI', ''],
  ['Curacao', 'CUW', ''],
  ['Japan', 'JPN', 'japon giappone'],
  ['Korea Republic', 'KOR', 'south korea korea corea del sur'],
  ['Korea DPR', 'PRK', 'dpr korea north korea'],
  ['IR Iran', 'IRN', 'iran'],
  ['Saudi Arabia', 'KSA', 'arabia saudi arabie saoudite'],
  ['Qatar', 'QAT', ''],
  ['Australia', 'AUS', ''],
  ['Jordan', 'JOR', ''],
  ['Uzbekistan', 'UZB', ''],
  ['Iraq', 'IRQ', ''],
  ['United Arab Emirates', 'UAE', 'uae'],
  ['China PR', 'CHN', 'china'],
  ['New Zealand', 'NZL', ''],
  ['Morocco', 'MAR', 'marruecos maroc marokko marocco'],
  ['Senegal', 'SEN', ''],
  ['Egypt', 'EGY', 'egipto egypte aegypten egitto'],
  ['Algeria', 'ALG', 'argelia algerie'],
  ['Tunisia', 'TUN', 'tunez tunisie'],
  ['Nigeria', 'NGA', ''],
  ['Ghana', 'GHA', ''],
  ['Cameroon', 'CMR', 'camerun cameroun'],
  ["Cote d'Ivoire", 'CIV', 'ivory coast cote d ivoire costa de marfil'],
  ['South Africa', 'RSA', 'sudafrica'],
  ['Cabo Verde', 'CPV', 'cape verde'],
  ['DR Congo', 'COD', 'congo dr'],
  ['Mali', 'MLI', ''],
].map(([name, tla, aliases]) => ({ name, shortName: name, tla, crest: null, national: true, extraAliases: aliases ? [aliases] : [] }));

// Split each alias blob into phrases: multi-word aliases are listed with single spaces,
// so we keep the blob's individual words AND known two/three-word phrases.
const PHRASES = [
  'paises bajos', 'pays bas', 'pays de galles', 'irlanda del norte', 'czech republic', 'bosnia herzegovina',
  'fyr macedonia', 'macedonia del norte', 'islas feroe', 'estados unidos', 'etats unis', 'south korea',
  'corea del sur', 'dpr korea', 'north korea', 'arabia saudi', 'arabie saoudite', 'ivory coast',
  'cote d ivoire', 'costa de marfil', 'cape verde', 'congo dr',
];

for (const n of NATIONS) {
  const blob = n.extraAliases[0] ?? '';
  const phrases = PHRASES.filter((p) => blob.includes(p));
  let rest = blob;
  for (const p of phrases) rest = rest.replace(p, ' ');
  n.extraAliases = [...phrases, ...rest.split(/\s+/).filter(Boolean)];
}
