// National teams: canonical names (as football-data.org spells them where known),
// FIFA codes, and the other names broadcasters use in titles (English variants and
// the Spanish/French/German/Italian names that show up on federation channels).
// Used for World Cup / Euros fixture matching and for discovering Nations League
// matches from video titles.

export const NATIONS = [
  ['England', 'ENG', 'inglaterra angleterre inghilterra engleska ingiltere anglia'],
  ['Spain', 'ESP', 'espana espagne spagna spanien spanija spanjolska ispanya hiszpania'],
  ['Germany', 'GER', 'alemania deutschland allemagne germania njemacka nemacka almanya niemcy nemecko'],
  ['France', 'FRA', 'francia frankreich fransa francja francie francuska'],
  ['Italy', 'ITA', 'italia italie italien italija italya'],
  ['Portugal', 'POR', 'portogallo portugalija portekiz portugalia'],
  ['Netherlands', 'NED', 'holland paises bajos pays bas niederlande olanda nederland holandija holandia hollandia hollanda nizozemska nizozemsko'],
  ['Belgium', 'BEL', 'belgica belgique belgien belgio belgija belcika belgia'],
  ['Switzerland', 'SUI', 'suiza suisse schweiz svizzera nati svicarska isvicre szwajcaria elvetia'],
  ['Croatia', 'CRO', 'croacia croatie kroatien croazia hrvatska hrvatska hirvatistan chorwacja'],
  ['Denmark', 'DEN', 'dinamarca danemark daenemark danimarca danmark danska danimarka dania'],
  ['Norway', 'NOR', 'noruega norvege norwegen norvegia norge norveska norvec norwegia'],
  ['Sweden', 'SWE', 'suecia suede schweden svezia sverige svedska isvec szwecja suedia'],
  ['Poland', 'POL', 'polonia pologne polen polska polska poljska polonya'],
  ['Austria', 'AUT', 'osterreich autriche oesterreich austrija avusturya'],
  ['Scotland', 'SCO', 'escocia ecosse schottland scozia skotska iskocya szkocja'],
  ['Wales', 'WAL', 'gales pays de galles vels galler walia'],
  ['Northern Ireland', 'NIR', 'irlanda del norte'],
  ['Republic of Ireland', 'IRL', 'ireland irlanda irlande irska'],
  ['Finland', 'FIN', 'finlandia finnland suomi'],
  ['Iceland', 'ISL', 'islandia islande island'],
  ['Czechia', 'CZE', 'czech republic chequia tchequie tschechien cesko ceska republika ceska cehia cekya czechy'],
  ['Slovakia', 'SVK', 'eslovaquia slovaquie slowakei slovensko'],
  ['Slovenia', 'SVN', 'eslovenia slovenie slowenien slovenija'],
  ['Hungary', 'HUN', 'hungria hongrie ungarn ungheria magyarorszag madarska macaristan wegry'],
  ['Romania', 'ROU', 'rumania roumanie rumanien romania rumunija rumunsko'],
  ['Bulgaria', 'BUL', 'bulgarie bulgarien'],
  ['Serbia', 'SRB', 'serbie serbien srbija sirbistan'],
  ['Montenegro', 'MNE', ''],
  ['Bosnia and Herzegovina', 'BIH', 'bosnia bosnia herzegovina'],
  ['North Macedonia', 'MKD', 'fyr macedonia macedonia del norte'],
  ['Albania', 'ALB', 'albanie albanien arnavutluk shqiperia'],
  ['Kosovo', 'KVX', ''],
  ['Greece', 'GRE', 'grecia grece griechenland ellada hellas grcka yunanistan grecja'],
  ['Turkey', 'TUR', 'turkiye turquia turquie turkei turkiye turska turcja'],
  ['Cyprus', 'CYP', 'chipre chypre zypern'],
  ['Israel', 'ISR', ''],
  ['Ukraine', 'UKR', 'ucrania ukraine ukraina'],
  ['Belarus', 'BLR', 'bielorrusia'],
  ['Russia', 'RUS', 'rusia'],
  ['Georgia', 'GEO', ''],
  ['Armenia', 'ARM', ''],
  ['Azerbaijan', 'AZE', 'azerbaiyan'],
  ['Kazakhstan', 'KAZ', 'kazajistan'],
  ['Estonia', 'EST', ''],
  ['Latvia', 'LVA', 'letonia'],
  ['Lithuania', 'LTU', 'lituania'],
  ['Moldova', 'MDA', 'moldavsko moldavia moldavie moldawien'],
  ['Luxembourg', 'LUX', 'luxemburgo luxemburg'],
  ['Liechtenstein', 'LIE', ''],
  ['Malta', 'MLT', ''],
  ['Andorra', 'AND', ''],
  ['San Marino', 'SMR', ''],
  ['Gibraltar', 'GIB', ''],
  ['Faroe Islands', 'FRO', 'islas feroe faroe'],
  // Rest of the world (World Cup)
  ['Brazil', 'BRA', 'brasil bresil brasilien'],
  ['Argentina', 'ARG', 'argentine argentinien'],
  ['Uruguay', 'URU', ''],
  ['Colombia', 'COL', 'colombie kolumbien'],
  ['Ecuador', 'ECU', 'equateur'],
  ['Paraguay', 'PAR', ''],
  ['Chile', 'CHI', 'chili'],
  ['Peru', 'PER', ''],
  ['Venezuela', 'VEN', ''],
  ['Bolivia', 'BOL', ''],
  ['United States', 'USA', 'usa usmnt estados unidos etats unis'],
  ['Mexico', 'MEX', 'mexique mexiko messico'],
  ['Canada', 'CAN', ''],
  ['Costa Rica', 'CRC', ''],
  ['Panama', 'PAN', ''],
  ['Jamaica', 'JAM', ''],
  ['Honduras', 'HON', ''],
  ['Haiti', 'HAI', ''],
  ['Curacao', 'CUW', ''],
  ['Japan', 'JPN', 'japon giappone'],
  ['Korea Republic', 'KOR', 'south korea korea corea del sur'],
  ['Korea DPR', 'PRK', 'dpr korea north korea'],
  ['IR Iran', 'IRN', 'iran'],
  ['Saudi Arabia', 'KSA', 'arabia saudi arabie saoudite'],
  ['Qatar', 'QAT', ''],
  ['Australia', 'AUS', ''],
  ['Jordan', 'JOR', ''],
  ['Uzbekistan', 'UZB', ''],
  ['Iraq', 'IRQ', ''],
  ['United Arab Emirates', 'UAE', 'uae'],
  ['China PR', 'CHN', 'china'],
  ['New Zealand', 'NZL', ''],
  ['Morocco', 'MAR', 'marruecos maroc marokko marocco'],
  ['Senegal', 'SEN', ''],
  ['Egypt', 'EGY', 'egipto egypte aegypten egitto'],
  ['Algeria', 'ALG', 'argelia algerie'],
  ['Tunisia', 'TUN', 'tunez tunisie'],
  ['Nigeria', 'NGA', ''],
  ['Ghana', 'GHA', ''],
  ['Cameroon', 'CMR', 'camerun cameroun'],
  ["Cote d'Ivoire", 'CIV', 'ivory coast cote d ivoire costa de marfil'],
  ['South Africa', 'RSA', 'sudafrica'],
  ['Cabo Verde', 'CPV', 'cape verde'],
  ['DR Congo', 'COD', 'congo dr'],
  ['Mali', 'MLI', ''],
].map(([name, tla, aliases]) => ({ name, shortName: name, tla, crest: null, national: true, extraAliases: aliases ? [aliases] : [] }));

// Split each alias blob into phrases: multi-word aliases are listed with single spaces,
// so we keep the blob's individual words AND known two/three-word phrases.
const PHRASES = [
  'paises bajos', 'pays bas', 'pays de galles', 'irlanda del norte', 'czech republic', 'bosnia herzegovina',
  'fyr macedonia', 'macedonia del norte', 'islas feroe', 'estados unidos', 'etats unis', 'south korea',
  'corea del sur', 'dpr korea', 'north korea', 'arabia saudi', 'arabie saoudite', 'ivory coast',
  'cote d ivoire', 'costa de marfil', 'cape verde', 'congo dr', 'ceska republika',
];

for (const n of NATIONS) {
  const blob = n.extraAliases[0] ?? '';
  const phrases = PHRASES.filter((p) => blob.includes(p));
  let rest = blob;
  for (const p of phrases) rest = rest.replace(p, ' ');
  n.extraAliases = [...phrases, ...rest.split(/\s+/).filter(Boolean)];
}
