#!/usr/bin/env node
// Generates the files behind /geo.json, the visitor's country as Netlify's CDN sees it.
//
// YouTube blocks videos by the country of the viewer's IP address, so that is the
// best signal for which highlights will play. Netlify's CDN already knows it: a
// redirect rule with a Country condition sends /geo.json to /geo/<CC>.json.
// No function, no third-party lookup, nothing stored.
//
// Output (git-ignored, regenerated on every build):
//   public/geo/<CC>.json   {"country":"CC"} for every country we know
//   public/geo/none.json   {"country":null}  (no match / local dev)
//   public/_redirects      one rule per country + the fallback

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const tz = JSON.parse(fs.readFileSync(path.join(root, 'src/lib/tz-country.json'), 'utf8'));
const countries = [...new Set([...Object.values(tz), 'XK'])].filter((c) => /^[A-Z]{2}$/.test(c)).sort();

const dir = path.join(root, 'public/geo');
fs.rmSync(dir, { recursive: true, force: true });
fs.mkdirSync(dir, { recursive: true });
for (const c of countries) fs.writeFileSync(path.join(dir, `${c}.json`), JSON.stringify({ country: c }));
fs.writeFileSync(path.join(dir, 'none.json'), JSON.stringify({ country: null }));

const rules = [
  '# Generated by scripts/gen-geo.mjs: do not edit.',
  '# /geo.json -> the visitor\'s country (Netlify GeoIP), first match wins.',
  ...countries.map((c) => `/geo.json  /geo/${c}.json  302  Country=${c.toLowerCase()}`),
  '/geo.json  /geo/none.json  302',
];
fs.writeFileSync(path.join(root, 'public/_redirects'), rules.join('\n') + '\n');
console.log(`geo: ${countries.length} countries`);
